/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import JPanel.JPNotificacion;
import JPanel.JPcliente;
import JPanel.JPempleado;
import JPanel.JPpelicula;
import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class Inventario extends javax.swing.JFrame {
    
     JPpelicula pelicula = new JPpelicula();
     JPcliente cliente = new JPcliente();
     JPempleado empleado = new JPempleado();
    
    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
        this.setLocationRelativeTo(null);
        Shape form = new RoundRectangle2D.Double(0,0,this.getBounds().width,this.getBounds().height,27,27);
        AWTUtilities.setWindowShape(this, form);
        
       
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPrincipal = new javax.swing.JPanel();
        JPmenu = new javax.swing.JPanel();
        Bempleados = new javax.swing.JButton();
        Bclientes = new javax.swing.JButton();
        Bpeliculas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JlCerrar = new javax.swing.JLabel();
        JLMinimizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        JPrincipal.setPreferredSize(new java.awt.Dimension(745, 647));

        javax.swing.GroupLayout JPrincipalLayout = new javax.swing.GroupLayout(JPrincipal);
        JPrincipal.setLayout(JPrincipalLayout);
        JPrincipalLayout.setHorizontalGroup(
            JPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        JPrincipalLayout.setVerticalGroup(
            JPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );

        getContentPane().add(JPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 745, 647));

        JPmenu.setBackground(new java.awt.Color(238, 112, 82));
        JPmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bempleados.setBackground(new java.awt.Color(238, 112, 82));
        Bempleados.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        Bempleados.setForeground(new java.awt.Color(255, 255, 255));
        Bempleados.setText("Empleados");
        Bempleados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Bempleados.setContentAreaFilled(false);
        Bempleados.setSelected(true);
        Bempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BempleadosActionPerformed(evt);
            }
        });
        JPmenu.add(Bempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 200, 60));

        Bclientes.setBackground(new java.awt.Color(238, 112, 82));
        Bclientes.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        Bclientes.setForeground(new java.awt.Color(255, 255, 255));
        Bclientes.setText("Clientes");
        Bclientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Bclientes.setContentAreaFilled(false);
        Bclientes.setSelected(true);
        Bclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BclientesActionPerformed(evt);
            }
        });
        JPmenu.add(Bclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 60));

        Bpeliculas.setBackground(new java.awt.Color(238, 112, 82));
        Bpeliculas.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        Bpeliculas.setForeground(new java.awt.Color(255, 255, 255));
        Bpeliculas.setText("Peliculas");
        Bpeliculas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Bpeliculas.setContentAreaFilled(false);
        Bpeliculas.setSelected(true);
        Bpeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpeliculasActionPerformed(evt);
            }
        });
        JPmenu.add(Bpeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User.png"))); // NOI18N
        JPmenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 90, 100));

        getContentPane().add(JPmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 690));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JlCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Multiply_32px.png"))); // NOI18N
        JlCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(JlCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 30, -1));

        JLMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        JLMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JLMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLMinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(JLMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 40, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 750, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JlCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null,"Desea salir del login?","Exit",dialog);
        if(result == 0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_JlCerrarMouseClicked

    private void JLMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLMinimizarMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_JLMinimizarMouseClicked

    private void BclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BclientesActionPerformed
 
        pelicula.setVisible(false);
        empleado.setVisible(false); 
                 
        cliente.setSize(745, 647);
        JPrincipal.add(cliente);
        JPrincipal.revalidate();
        JPrincipal.repaint();
        cliente.setVisible(true);
    }//GEN-LAST:event_BclientesActionPerformed

    private void BpeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpeliculasActionPerformed
        
       //Hace invisible los demás JPanel
        empleado.setVisible(false);
        cliente.setVisible(false);
         
        //Añade el jPanel peliculas al panel principal y hace visible
        pelicula.setSize(745, 616);
        JPrincipal.add(pelicula);
        JPrincipal.revalidate();
        JPrincipal.repaint();
        pelicula.setVisible(true);
        
       
    }//GEN-LAST:event_BpeliculasActionPerformed

    private void BempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BempleadosActionPerformed
        
        
        pelicula.setVisible(false);
        cliente.setVisible(false);
        
        
        empleado.setSize(710, 460);
        JPrincipal.add(empleado);
        JPrincipal.revalidate();
        JPrincipal.repaint();
        empleado.setVisible(true);
        
    }//GEN-LAST:event_BempleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bclientes;
    private javax.swing.JButton Bempleados;
    private javax.swing.JButton Bpeliculas;
    private javax.swing.JLabel JLMinimizar;
    private javax.swing.JPanel JPmenu;
    private javax.swing.JPanel JPrincipal;
    private javax.swing.JLabel JlCerrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
