/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrame;

/**
 *
 * @author nicol
 */
public class iFalquiler extends javax.swing.JInternalFrame {

    /**
     * Creates new form iFalquiler
     */
    public iFalquiler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPinformacionPeliculs = new javax.swing.JPanel();
        jLid = new javax.swing.JLabel();
        jLtitulo = new javax.swing.JLabel();
        jLlenguaje = new javax.swing.JLabel();
        jLctegoria = new javax.swing.JLabel();
        jLprecio = new javax.swing.JLabel();
        jLduracion = new javax.swing.JLabel();
        jLsinopsis = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscador3.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 50, 40));

        jTextField1.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setText("Ingrese el título...");
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 330, 40));

        jLabel1.setBackground(new java.awt.Color(238, 112, 82));
        jLabel1.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 112, 82));
        jLabel1.setText("Buscar:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 60, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 750, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 150, 210));

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 112, 82));
        jLabel3.setText("Sinopsis:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 600, 100));

        jButton2.setBackground(new java.awt.Color(238, 112, 82));
        jButton2.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(238, 112, 82));
        jButton2.setText("Alquilar");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 80, 30));

        jPinformacionPeliculs.setBackground(new java.awt.Color(255, 255, 255));
        jPinformacionPeliculs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLid.setBackground(new java.awt.Color(238, 112, 82));
        jLid.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLid.setForeground(new java.awt.Color(238, 112, 82));
        jLid.setText("ID pelicula:");
        jPinformacionPeliculs.add(jLid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLtitulo.setBackground(new java.awt.Color(238, 112, 82));
        jLtitulo.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLtitulo.setForeground(new java.awt.Color(238, 112, 82));
        jLtitulo.setText("Título:");
        jLtitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPinformacionPeliculs.add(jLtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 30));

        jLlenguaje.setBackground(new java.awt.Color(238, 112, 82));
        jLlenguaje.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLlenguaje.setForeground(new java.awt.Color(238, 112, 82));
        jLlenguaje.setText("Lenguajes:");
        jPinformacionPeliculs.add(jLlenguaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLctegoria.setBackground(new java.awt.Color(238, 112, 82));
        jLctegoria.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLctegoria.setForeground(new java.awt.Color(238, 112, 82));
        jLctegoria.setText("Categoría:");
        jPinformacionPeliculs.add(jLctegoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLprecio.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLprecio.setForeground(new java.awt.Color(238, 112, 82));
        jLprecio.setText("Precio:");
        jPinformacionPeliculs.add(jLprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLduracion.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLduracion.setForeground(new java.awt.Color(238, 112, 82));
        jLduracion.setText("Duración:");
        jPinformacionPeliculs.add(jLduracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 70, -1));

        jLsinopsis.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLsinopsis.setForeground(new java.awt.Color(238, 112, 82));
        jLsinopsis.setText("Actores:");
        jPinformacionPeliculs.add(jLsinopsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jPanel4.add(jPinformacionPeliculs, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 430, 290));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 750, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        //<---

    }//GEN-LAST:event_jButton2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLctegoria;
    private javax.swing.JLabel jLduracion;
    private javax.swing.JLabel jLid;
    private javax.swing.JLabel jLlenguaje;
    private javax.swing.JLabel jLprecio;
    private javax.swing.JLabel jLsinopsis;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPinformacionPeliculs;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
